import type { Metadata } from "next";
import "./globals.css";
import { GlobalNavigation } from "@/components/GlobalNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-zenmaru relative text-zinc-500 min-h-svh mx-auto pt-20 pb-40 scroll-px-10">
        {children}
        <GlobalNavigation />
      </body>
    </html>
  );
}
